/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inmuebles;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author mauri
 */
public class IniciarSesion extends javax.swing.JFrame
{

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaContrasenia = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contrasenia = new javax.swing.JPasswordField();
        btn_Ingresar = new javax.swing.JButton();
        olvideContrasenia = new javax.swing.JLabel();
        etiquetaO = new javax.swing.JLabel();
        btn_CrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar Sesión");

        etiquetaUsuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        etiquetaUsuario.setText("Usuario:");

        etiquetaContrasenia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        etiquetaContrasenia.setText("Contraseña:");

        usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        contrasenia.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btn_Ingresar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_IngresarActionPerformed(evt);
            }
        });

        olvideContrasenia.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        olvideContrasenia.setText("Olvide mi contraseña");
        olvideContrasenia.setToolTipText("");
        olvideContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        etiquetaO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        etiquetaO.setText("o");

        btn_CrearCuenta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_CrearCuenta.setText("Crear una cuenta");
        btn_CrearCuenta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_CrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaUsuario)
                            .addComponent(etiquetaContrasenia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usuario)
                            .addComponent(contrasenia)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Ingresar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(etiquetaO)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(olvideContrasenia)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(btn_CrearCuenta)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaUsuario)
                    .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaContrasenia)
                    .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Ingresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(olvideContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaO)
                .addGap(18, 18, 18)
                .addComponent(btn_CrearCuenta)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrearCuentaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_CrearCuentaActionPerformed
    {//GEN-HEADEREND:event_btn_CrearCuentaActionPerformed
        // TODO add your handling code here:
        CrearCuenta cC = new CrearCuenta();
        cC.setVisible(true);
    }//GEN-LAST:event_btn_CrearCuentaActionPerformed

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_IngresarActionPerformed
    {//GEN-HEADEREND:event_btn_IngresarActionPerformed
        // TODO add your handling code here:
        if (usuario.getText().equals("ITTOL") && contrasenia.getText().equals("1234"))
        {
            JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso");
            InterfazPrincipal.iniciar_Sesion.setEnabled(false);
            InterfazPrincipal.iniciar_Sesion.setVisible(false);
            InterfazPrincipal.perfil.setEnabled(true);
            InterfazPrincipal.perfil.setVisible(true);
            this.dispose();
        } else if (usuario.getText().equals("ITTOL") && !contrasenia.getText().equals("1234"))
        {
            JOptionPane.showMessageDialog(null, "La contraseña es incorrecta", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else
        {
            JOptionPane.showMessageDialog(null, "El usuario y la contraseña son incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CrearCuenta;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JLabel etiquetaContrasenia;
    private javax.swing.JLabel etiquetaO;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel olvideContrasenia;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
